# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [article]
  autogenerate: [article]

- name: samuelhall
  elements: [article]

- name: projects
  elements: [article]

- name: releases
  elements: [article]
